# Generated by Django 3.0.5 on 2020-05-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('fId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('layers', models.IntegerField()),
                ('roomNum', models.IntegerField()),
                ('openTime', models.TimeField()),
            ],
            options={
                'db_table': 'flat',
            },
        ),
    ]
