# Generated by Django 3.0.5 on 2020-05-14 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('chargeType', models.CharField(choices=[('W', 'Water'), ('F', 'Food'), ('E', 'Electricity'), ('A', 'Accommodation'), ('T', 'Trash')], default='W', max_length=4)),
                ('cId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('chargeDate', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dormitoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dormitory')),
                ('flatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
            ],
            options={
                'db_table': 'charges',
            },
        ),
    ]
