# Generated by Django 3.0.5 on 2020-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('nation', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('classId', models.IntegerField()),
                ('telephone', models.CharField(max_length=100)),
                ('flatId', models.IntegerField()),
                ('dormitoryId', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
