# Generated by Django 3.0.5 on 2020-05-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('nation', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('classId', models.IntegerField()),
                ('telephone', models.CharField(max_length=100)),
                ('dormitoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dormitory')),
                ('flatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
