# Generated by Django 3.0.5 on 2020-05-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('S', 'S'), ('F', 'A'), ('C', 'C')], default='C', max_length=2)),
                ('uId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
