# Generated by Django 3.0.5 on 2020-05-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('S', 'Super'), ('A', 'Admin'), ('C', 'Common')], default='C', max_length=3)),
                ('student_add', models.BooleanField()),
                ('student_edit', models.BooleanField()),
                ('student_delete', models.BooleanField()),
                ('flat_add', models.BooleanField()),
                ('flat_edit', models.BooleanField()),
                ('flat_delete', models.BooleanField()),
                ('dormitory_add', models.BooleanField()),
                ('dormitory_edit', models.BooleanField()),
                ('dormitory_delete', models.BooleanField()),
                ('charge_add', models.BooleanField()),
                ('charge_edit', models.BooleanField()),
                ('charge_delete', models.BooleanField()),
                ('user_add', models.BooleanField()),
                ('user_edit', models.BooleanField()),
                ('user_delete', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
