# Generated by Django 3.0.5 on 2020-05-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeType', models.CharField(choices=[('W', 'Water'), ('F', 'Food'), ('E', 'Electricity'), ('A', 'Accommodation')], default='W', max_length=4)),
                ('cId', models.IntegerField()),
                ('flatId', models.IntegerField()),
                ('dormitoryId', models.IntegerField()),
                ('chargeDate', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'charge',
            },
        ),
    ]
