# Generated by Django 3.0.5 on 2020-05-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dormitory', '0001_initial'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeType', models.CharField(choices=[('W', 'Water'), ('F', 'Food'), ('E', 'Electricity'), ('A', 'Accommodation')], default='W', max_length=4)),
                ('cId', models.IntegerField()),
                ('chargeDate', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dormitoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.Dormitory')),
                ('flatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
            ],
            options={
                'db_table': 'charge',
            },
        ),
    ]
